version: '3.5'

services:
  telegram-db-bot:
    image: mitto98/telegram-downloader-bot:latest
    environment:
      TELEGRAM_BOT_TOKEN: "1450402032:AAFilQj1KK1lEfdXsZ3yFaLxMKnTcdYOvEU"
      TELEGRAM_CHAT_ID: "921428507"
    volumes:
       - ./downloads:/downloads
    restart: unless-stopped
